export interface Job {
  id: string;
  title: string;
  company: string;
  companyLogo?: string;
  location: string;
  type: 'Full-time' | 'Part-time' | 'Contract' | 'Remote' | 'Hybrid';
  experience: string;
  salaryMin: number;
  salaryMax: number;
  skills: string[];
  description: string;
  responsibilities: string[];
  requirements: string[];
  postedAt: string;
  industry: string;
  remote: boolean;
  featured?: boolean;
}

export const JOBS: Job[] = [
  {
    id: 'job-001',
    title: 'Senior Software Engineer – Backend',
    company: 'Razorpay',
    location: 'Bangalore, Karnataka',
    type: 'Hybrid',
    experience: '4–7 years',
    salaryMin: 3000000,
    salaryMax: 5500000,
    skills: ['Node.js', 'Go', 'PostgreSQL', 'Redis', 'Kafka', 'AWS'],
    description: 'Join Razorpay\'s core payments infrastructure team and build systems that process millions of transactions daily. You\'ll work on reliability, performance, and new payment products.',
    responsibilities: [
      'Design and build high-throughput payment processing services',
      'Lead technical design reviews and code reviews',
      'Mentor junior engineers and drive best practices',
      'Collaborate with product teams to deliver features end-to-end',
      'Ensure 99.99% uptime for critical payment flows',
    ],
    requirements: [
      '4+ years of backend development experience',
      'Strong proficiency in Node.js or Go',
      'Experience with distributed systems and microservices',
      'Deep understanding of database design and optimization',
      'Familiarity with fintech/payments domain is a plus',
    ],
    postedAt: '2026-04-18',
    industry: 'Fintech',
    remote: false,
    featured: true,
  },
  {
    id: 'job-002',
    title: 'ML Engineer – Recommendations',
    company: 'Zepto',
    location: 'Mumbai, Maharashtra',
    type: 'Hybrid',
    experience: '2–5 years',
    salaryMin: 2500000,
    salaryMax: 4500000,
    skills: ['Python', 'TensorFlow', 'PyTorch', 'MLflow', 'Spark', 'SQL'],
    description: 'Build next-generation recommendation systems that delight 10M+ users. You\'ll own models from idementation to production serving.',
    responsibilities: [
      'Build and maintain personalized recommendation models',
      'Run A/B tests and analyse impact on key business metrics',
      'Build real-time model serving infrastructure',
      'Work with data engineers to improve data pipelines',
    ],
    requirements: [
      '2+ years of ML engineering experience',
      'Strong Python skills and knowledge of ML frameworks',
      'Experience deploying models at scale',
      'Good understanding of recommendation systems or NLP',
    ],
    postedAt: '2026-04-17',
    industry: 'Quick Commerce',
    remote: false,
    featured: true,
  },
  {
    id: 'job-003',
    title: 'Full Stack Engineer',
    company: 'CRED',
    location: 'Bangalore, Karnataka',
    type: 'Hybrid',
    experience: '3–6 years',
    salaryMin: 2800000,
    salaryMax: 5000000,
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'PostgreSQL', 'Docker'],
    description: 'Help build CRED\'s award-winning product experience for India\'s premium credit card users. Shape the intersection of design and engineering.',
    responsibilities: [
      'Build performant, accessible UI components',
      'Develop and maintain GraphQL APIs',
      'Improve application performance and Core Web Vitals',
      'Collaborate with design and product teams',
    ],
    requirements: [
      '3+ years of full-stack development experience',
      'Proficiency in React and Node.js',
      'Experience with TypeScript and GraphQL',
      'Strong eye for design and UX',
    ],
    postedAt: '2026-04-16',
    industry: 'Fintech',
    remote: false,
  },
  {
    id: 'job-004',
    title: 'DevOps Engineer – Cloud Infrastructure',
    company: 'PhonePe',
    location: 'Pune, Maharashtra',
    type: 'Full-time',
    experience: '3–6 years',
    salaryMin: 2200000,
    salaryMax: 4000000,
    skills: ['Kubernetes', 'Terraform', 'AWS', 'GCP', 'Prometheus', 'Python', 'Helm'],
    description: 'Join PhonePe\'s infrastructure team to build and maintain scalable cloud infrastructure handling 250M+ users.',
    responsibilities: [
      'Manage Kubernetes clusters across multiple cloud providers',
      'Build CI/CD pipelines with zero-downtime deployments',
      'Implement infrastructure as code with Terraform',
      'Drive SRE practices and incident response',
    ],
    requirements: [
      '3+ years of DevOps/SRE experience',
      'Hands-on experience with Kubernetes and Docker',
      'Strong knowledge of cloud platforms (AWS/GCP)',
      'Experience with monitoring and observability tools',
    ],
    postedAt: '2026-04-15',
    industry: 'Payments',
    remote: false,
  },
  {
    id: 'job-005',
    title: 'Software Engineer II – Frontend',
    company: 'Meesho',
    location: 'Remote',
    type: 'Remote',
    experience: '2–4 years',
    salaryMin: 1800000,
    salaryMax: 3200000,
    skills: ['React', 'TypeScript', 'Next.js', 'TailwindCSS', 'Redux', 'Jest'],
    description: 'Build Meesho\'s seller and buyer apps used by 150M+ users across India. Create highly performant React applications with great UX.',
    responsibilities: [
      'Build and ship new product features end-to-end',
      'Optimise app performance for low-bandwidth networks',
      'Write comprehensive unit and integration tests',
      'Participate in design reviews and architecture decisions',
    ],
    requirements: [
      '2+ years of frontend development experience',
      'Expert knowledge of React and TypeScript',
      'Experience with performance optimisation',
      'Understanding of accessibility standards',
    ],
    postedAt: '2026-04-14',
    industry: 'E-commerce',
    remote: true,
  },
  {
    id: 'job-006',
    title: 'Data Engineer',
    company: 'Swiggy',
    location: 'Bangalore, Karnataka',
    type: 'Hybrid',
    experience: '2–5 years',
    salaryMin: 1800000,
    salaryMax: 3500000,
    skills: ['Apache Spark', 'Airflow', 'Python', 'SQL', 'dbt', 'Snowflake', 'Kafka'],
    description: 'Join Swiggy\'s data platform team to build world-class data infrastructure supporting real-time food delivery operations.',
    responsibilities: [
      'Design and maintain scalable data pipelines',
      'Build data models and analytical frameworks',
      'Optimize query performance across petabyte-scale datasets',
      'Partner with analytics and ML teams',
    ],
    requirements: [
      '2+ years of data engineering experience',
      'Proficiency in Python and SQL',
      'Experience with Apache Spark and workflow orchestration',
      'Familiarity with cloud data warehouses',
    ],
    postedAt: '2026-04-13',
    industry: 'Food Tech',
    remote: false,
  },
  {
    id: 'job-007',
    title: 'Product Manager – AI Features',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    type: 'Hybrid',
    experience: '4–8 years',
    salaryMin: 3500000,
    salaryMax: 6000000,
    skills: ['Product Management', 'AI/ML', 'Data Analysis', 'Roadmap Planning', 'Agile'],
    description: 'Lead the AI product strategy for Freshworks CRM suite. Define, ship, and iterate on AI features that delight 60,000+ business customers globally.',
    responsibilities: [
      'Define product strategy and roadmap for AI features',
      'Work closely with engineering and design teams',
      'Analyze customer data to drive product decisions',
      'Manage stakeholders across multiple geographies',
    ],
    requirements: [
      '4+ years of product management experience',
      'Strong understanding of AI/ML capabilities',
      'Experience with B2B SaaS products',
      'Excellent analytical and communication skills',
    ],
    postedAt: '2026-04-12',
    industry: 'SaaS',
    remote: false,
  },
  {
    id: 'job-008',
    title: 'Senior Android Engineer',
    company: 'Groww',
    location: 'Bangalore, Karnataka',
    type: 'Hybrid',
    experience: '4–7 years',
    salaryMin: 2500000,
    salaryMax: 5000000,
    skills: ['Kotlin', 'Android SDK', 'Coroutines', 'Jetpack Compose', 'MVVM', 'GraphQL'],
    description: 'Build Groww\'s trading and investment app used by 7M+ active investors. Own critical trading flows and deliver fast, beautiful Android experiences.',
    responsibilities: [
      'Build and improve core trading flows',
      'Implement animations and micro-interactions',
      'Work on performance and crash reduction',
      'Drive technical architecture decisions',
    ],
    requirements: [
      '4+ years of Android development experience',
      'Expert Kotlin skills with Coroutines knowledge',
      'Experience with Jetpack Compose',
      'Understanding of fintech security requirements',
    ],
    postedAt: '2026-04-11',
    industry: 'Fintech',
    remote: false,
  },
  {
    id: 'job-009',
    title: 'Staff Engineer – Platform',
    company: 'Dunzo',
    location: 'Remote',
    type: 'Remote',
    experience: '7–12 years',
    salaryMin: 5000000,
    salaryMax: 9000000,
    skills: ['System Design', 'Go', 'Kubernetes', 'gRPC', 'PostgreSQL', 'Redis'],
    description: 'Lead architectural decisions for Dunzo\'s platform. Own critical services that power last-mile delivery for 5 cities.',
    responsibilities: [
      'Define and drive platform engineering strategy',
      'Lead cross-team technical initiatives',
      'Build scalable microservices with Go',
      'Mentor senior engineers across teams',
    ],
    requirements: [
      '7+ years of software engineering experience',
      'Experience building large-scale distributed systems',
      'Strong leadership and communication skills',
      'Track record of delivering complex technical projects',
    ],
    postedAt: '2026-04-10',
    industry: 'Quick Commerce',
    remote: true,
    featured: true,
  },
  {
    id: 'job-010',
    title: 'Security Engineer',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh',
    type: 'Full-time',
    experience: '3–6 years',
    salaryMin: 2000000,
    salaryMax: 4000000,
    skills: ['AppSec', 'Penetration Testing', 'SAST/DAST', 'AWS Security', 'Python', 'Burp Suite'],
    description: 'Join Paytm\'s security team to protect one of India\'s largest payment platforms. Drive application security, threat modeling, and security engineering.',
    responsibilities: [
      'Conduct security assessments and penetration testing',
      'Integrate security tooling into CI/CD pipelines',
      'Lead threat modeling exercises with engineering teams',
      'Respond to security incidents and vulnerabilities',
    ],
    requirements: [
      '3+ years of application security experience',
      'Experience with OWASP Top 10 and secure coding practices',
      'Knowledge of cloud security in AWS',
      'CEH, OSCP, or equivalent certification preferred',
    ],
    postedAt: '2026-04-09',
    industry: 'Fintech',
    remote: false,
  },
  {
    id: 'job-011',
    title: 'Frontend Engineer – Design Systems',
    company: 'InMobi',
    location: 'Bangalore, Karnataka',
    type: 'Hybrid',
    experience: '3–5 years',
    salaryMin: 2000000,
    salaryMax: 3800000,
    skills: ['React', 'TypeScript', 'Storybook', 'CSS', 'Accessibility', 'Design Tokens'],
    description: 'Build and maintain InMobi\'s design system used across 15+ product teams. Create reusable components with accessibility baked in.',
    responsibilities: [
      'Develop and maintain shared component library',
      'Create design tokens and theming system',
      'Write comprehensive Storybook documentation',
      'Work closely with designers on component specs',
    ],
    requirements: [
      '3+ years of frontend engineering experience',
      'Deep expertise in React and TypeScript',
      'Experience building or contributing to design systems',
      'Strong understanding of accessibility (WCAG 2.1)',
    ],
    postedAt: '2026-04-08',
    industry: 'AdTech',
    remote: false,
  },
  {
    id: 'job-012',
    title: 'AI/ML Research Engineer',
    company: 'Sarvam AI',
    location: 'Bangalore, Karnataka',
    type: 'Full-time',
    experience: '2–6 years',
    salaryMin: 3000000,
    salaryMax: 7000000,
    skills: ['Python', 'PyTorch', 'Transformers', 'NLP', 'LLMs', 'CUDA', 'Research'],
    description: 'Work at the frontier of AI research focused on Indian languages. Build and train large language models for Bharat.',
    responsibilities: [
      'Research and implement state-of-the-art NLP models',
      'Pre-train and fine-tune LLMs on Indian language datasets',
      'Publish research papers and contribute to open source',
      'Collaborate with linguists and domain experts',
    ],
    requirements: [
      'Strong background in deep learning and NLP',
      'Experience training large transformer models',
      'Familiarity with Indian languages is a plus',
      'Publications in top ML/NLP conferences preferred',
    ],
    postedAt: '2026-04-07',
    industry: 'AI Research',
    remote: false,
    featured: true,
  },
  {
    id: 'job-013',
    title: 'Backend Engineer – Go/Rust',
    company: 'Hasura',
    location: 'Remote',
    type: 'Remote',
    experience: '3–7 years',
    salaryMin: 3000000,
    salaryMax: 6000000,
    skills: ['Go', 'Rust', 'GraphQL', 'PostgreSQL', 'Distributed Systems', 'Docker'],
    description: 'Join Hasura\'s core team building the world\'s most popular GraphQL engine. Work on open-source technology used by 100K+ developers worldwide.',
    responsibilities: [
      'Implement new features in the GraphQL engine',
      'Improve query planning and execution performance',
      'Contribute to open source and engage with community',
      'Write comprehensive tests and documentation',
    ],
    requirements: [
      '3+ years of backend development with systems languages',
      'Experience with Go or Rust',
      'Understanding of database internals and query optimization',
      'Open source contributions are a big plus',
    ],
    postedAt: '2026-04-06',
    industry: 'Developer Tools',
    remote: true,
  },
  {
    id: 'job-014',
    title: 'Senior Data Scientist',
    company: 'OYO Rooms',
    location: 'Gurugram, Haryana',
    type: 'Hybrid',
    experience: '4–8 years',
    salaryMin: 2500000,
    salaryMax: 5000000,
    skills: ['Python', 'Machine Learning', 'Statistics', 'SQL', 'Tableau', 'NLP'],
    description: 'Lead data science initiatives for OYO\'s revenue management and demand forecasting systems. Influence pricing for 1.5M+ hotel rooms globally.',
    responsibilities: [
      'Build and own demand forecasting models',
      'Drive dynamic pricing algorithms',
      'Collaborate with product and business teams',
      'Present insights to C-suite stakeholders',
    ],
    requirements: [
      '4+ years of data science experience',
      'Strong statistical modelling and ML skills',
      'Experience with forecasting/time-series analysis',
      'Excellent communication and business acumen',
    ],
    postedAt: '2026-04-05',
    industry: 'Hospitality Tech',
    remote: false,
  },
  {
    id: 'job-015',
    title: 'Engineering Manager – Growth',
    company: 'ShareChat',
    location: 'Bangalore, Karnataka',
    type: 'Hybrid',
    experience: '6–10 years',
    salaryMin: 4500000,
    salaryMax: 8000000,
    skills: ['Engineering Leadership', 'Growth Hacking', 'A/B Testing', 'System Design', 'Python'],
    description: 'Lead a team of 8 engineers building growth products for ShareChat\'s 180M monthly active users across regional languages.',
    responsibilities: [
      'Manage and grow a team of 6–10 engineers',
      'Drive engineering strategy for growth initiatives',
      'Build experimentation and personalisation infrastructure',
      'Partner with product and business leaders',
    ],
    requirements: [
      '6+ years of engineering experience',
      '2+ years of people management experience',
      'Track record of driving measurable growth',
      'Strong system design skills',
    ],
    postedAt: '2026-04-04',
    industry: 'Social Media',
    remote: false,
  },
];

export const INDUSTRIES = [
  'Fintech', 'E-commerce', 'Food Tech', 'Quick Commerce', 'SaaS',
  'AI Research', 'Developer Tools', 'AdTech', 'Social Media',
  'Hospitality Tech', 'Payments', 'EdTech', 'HealthTech',
];

export const JOB_TYPES = ['Full-time', 'Part-time', 'Contract', 'Remote', 'Hybrid'];

export const EXPERIENCE_LEVELS = [
  { label: '0–2 years (Fresher)', min: 0, max: 2 },
  { label: '2–5 years (Mid-level)', min: 2, max: 5 },
  { label: '5–8 years (Senior)', min: 5, max: 8 },
  { label: '8+ years (Lead/Staff)', min: 8, max: 99 },
];
